### ISSUE TITLE
All large whisper models missing from huggingface repo

### ISSUE THREAD

**Issue by halalsandwich** [echogarden-project/echogarden#32]
large-v1 and large-v2 are missing

Prepare for speech translation.. 182.9ms
Preprocess audio for translation.. 0.4ms
Load whisper module.. nulled\node_modules\.pnpm\gaxios@6.1.1\node_modules\gaxios\build\src\gaxios.js:141
                throw new common_1.GaxiosError(`Request failed with status code ${translatedResponse.status}`, opts, translatedResponse);
                      ^

GaxiosError: Request failed with status code 404
    at Gaxios._request (nulled\node_modules\.pnpm\gaxios@6.1.1\node_modules\gaxios\build\src\gaxios.js:141:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async downloadFile (file:///nulled/node_modules/.pnpm/echogarden@0.11.17/node_modules/echogarden/dist/utilities/FileDownloader.js:34:22)
    at async downloadAndExtractTarball (file:///nulled/node_modules/.pnpm/echogarden@0.11.17/node_modules/echogarden/dist/utilities/FileDownloader.js:16:5)
    at async loadPackage (file:///nulled/node_modules/.pnpm/echogarden@0.11.17/node_modules/echogarden/dist/utilities/PackageManager.js:18:5)
    at async Module.loadPackagesAndGetPaths (file:///nulled/node_modules/.pnpm/echogarden@0.11.17/node_modules/echogarden/dist/recognition/WhisperSTT.js:951:22)
    at async Module.translateSpeech (file:///nulled/node_modules/.pnpm/echogarden@0.11.17/node_modules/echogarden/dist/API/Translation.js:44:59) {
  config: {
    url: 'https://huggingface.co/echogarden/echogarden-packages/resolve/main/whisper-large-v2-20230718.tar.gz',
    headers: {},
    responseType: 'stream',
    paramsSerializer: [Function: paramsSerializer],
    validateStatus: [Function: validateStatus],
    method: 'GET',
    errorRedactor: [Function: defaultErrorRedactor]
  },
  response: {
    config: {
      url: 'https://huggingface.co/echogarden/echogarden-packages/resolve/main/whisper-large-v2-20230718.tar.gz',
      headers: {},
      responseType: 'stream',
      paramsSerializer: [Function: paramsSerializer],
      validateStatus: [Function: validateStatus],
      method: 'GET',
      errorRedactor: [Function: defaultErrorRedactor]
    },
    data: 'Entry not found',
    headers: {
      'access-control-allow-origin': 'https://huggingface.co',
      'access-control-expose-headers': 'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,ETag,Link,Accept-Ranges,Content-Range',
      connection: 'keep-alive',
      'content-length': '15',
      'content-type': 'text/plain; charset=utf-8',
      vary: 'Origin',
      'x-cache': 'Error from cloudfront',
      'x-error-code': 'EntryNotFound',
      'x-error-message': 'Entry not found',
      'x-powered-by': 'huggingface-moon',
    },
    status: 404,
    statusText: 'Not Found',
    request: {
      responseURL: 'https://huggingface.co/echogarden/echogarden-packages/resolve/main/whisper-large-v2-20230718.tar.gz'
    }
  },
  error: undefined,
  status: 404
}

Node.js v20.6.1

**Comment by rotemdan** [comment]
Yes. They are not currently supported.

Reasons:
* I'm using a special conversion script I wrote to convert a modified version of the core Whisper source code, to ONNX.
* Doing the conversion to ONNX, for the large models, requires a huge amount of RAM (probably on the scale of 40GB - 60GB? of virtual memory), which I don't have. It's still possible to run via virtual memory (swapping) but it would possibly take several hours (I never even tried).
* The converted model disk sizes would be on the order of 4GB - 8GB or more.
* Inference with such large models on CPU only would be very slow (since `onnxruntime-node` supports only CPU inference).
* The memory requirement of running the large models would be pretty large (possibly 4GB - 8GB or more - I don't know exactly).
* Testing the large models would be very slow (but still possible).

**Despite all these setbacks:** It **is** possible to do the conversion at least and upload the ONNX models, and I would like. It should work (since all smaller models do).

Also, the new `large-v3` is also worth to try.

The special exporter Python script, with a custom version of the original Python code, is in this repository:

https://github.com/echogarden-project/whisper-onnx-exporter

You can try exporting the large models yourself (there are instructions and the script is easy to run and has no significant dependencies).

If you manage to do the export please let me know (interesting how large the files would be), I'll upload it to Hugging Face.

I might try to perform the export myself but I'm not sure if my PC would be able to handle it (that's the only reason I haven't tried yet!).

**Comment by halalsandwich** [comment]
40-60gb doesn't sound too bad, I'm sure you can rent a server temporarily and get it done in a fair amount of time

**Comment by rotemdan** [comment]
Sure, but this project is done on virtually a zero budget (actually a higher priority for me would be to rent a cloud macOS VM to sort out some macOS issues).

The Echogarden model repository was originally hosted on GitHub, which has a limit of 2GB uploads, so back than, even if I did manage to export the models, I wouldn't have been able to upload them anyway. Several months later, I moved it to Hugging Face, which doesn't have that restriction.

The size of each of original large models if 3GB. The ONNX version would be at least twice larger. It's a huge download but Hugging Face does make it possible.

Here are links for original `.pt` (PyTorch) models (from the [original Whisper codebase](https://github.com/openai/whisper/blob/e58f28804528831904c3b6f2c0e473f346223433/whisper/__init__.py#L18)):

```py
_MODELS = {
    "tiny.en": "https://openaipublic.azureedge.net/main/whisper/models/d3dd57d32accea0b295c96e26691aa14d8822fac7d9d27d5dc00b4ca2826dd03/tiny.en.pt",
    "tiny": "https://openaipublic.azureedge.net/main/whisper/models/65147644a518d12f04e32d6f3b26facc3f8dd46e5390956a9424a650c0ce22b9/tiny.pt",
    "base.en": "https://openaipublic.azureedge.net/main/whisper/models/25a8566e1d0c1e2231d1c762132cd20e0f96a85d16145c3a00adf5d1ac670ead/base.en.pt",
    "base": "https://openaipublic.azureedge.net/main/whisper/models/ed3a0b6b1c0edf879ad9b11b1af5a0e6ab5db9205f891f668f8b0e6c6326e34e/base.pt",
    "small.en": "https://openaipublic.azureedge.net/main/whisper/models/f953ad0fd29cacd07d5a9eda5624af0f6bcf2258be67c92b79389873d91e0872/small.en.pt",
    "small": "https://openaipublic.azureedge.net/main/whisper/models/9ecf779972d90ba49c06d968637d720dd632c55bbf19d441fb42bf17a411e794/small.pt",
    "medium.en": "https://openaipublic.azureedge.net/main/whisper/models/d7440d1dc186f76616474e0ff0b3b6b879abc9d1a4926b7adfa41db2d497ab4f/medium.en.pt",
    "medium": "https://openaipublic.azureedge.net/main/whisper/models/345ae4da62f9b3d59415adc60127b97c714f32e89e936602e85993674d08dcb1/medium.pt",
    "large-v1": "https://openaipublic.azureedge.net/main/whisper/models/e4b87e7e0bf463eb8e6956e646f1e277e901512310def2c24bf0e11bd3c28e9a/large-v1.pt",
    "large-v2": "https://openaipublic.azureedge.net/main/whisper/models/81f7c96c852ee8fc832187b0132e569d6c3065a3252ed18e56effd0b6a73e524/large-v2.pt",
    "large-v3": "https://openaipublic.azureedge.net/main/whisper/models/e5b1a55b89c1367dacf97e3e19bfd829a01529dbfdeefa8caeb59b3f1b81dadb/large-v3.pt",
    "large": "https://openaipublic.azureedge.net/main/whisper/models/e5b1a55b89c1367dacf97e3e19bfd829a01529dbfdeefa8caeb59b3f1b81dadb/large-v3.pt",
}
```

The conversion simply requires download one of these PyTorch models, place them in the `pytorch-models` and running:

```
python export-whisper-onnx.py [model-name]
```
like:
```
python export-whisper-onnx.py tiny
```

You can try yourself if you want.

I'm currently downloading the large models myself. It will take time until it'll finish. I'll try to run the conversion overnight but I'm not sure if my PC would handle it (I only have 8GB of RAM). It's possible this would take as much several days to run, since my SSD is also SATA (max 500MB/s), so swapping wouldn't be very fast.

If I recall correctly it did the `medium` model in about an hour? I don't remember, but it allocated about 20GB of virtual memory.

**Comment by rotemdan** [comment]
I tried to perform the export of `large-v3`. It got to about 26GB of allocated RAM and abruptly exited without any error message. It's possible it was out of memory. I'm not sure what the problem is. I'll try to investigate it in the next days maybe. Maybe try `large-v1` and `large-v2` or try to use verbose mode. We'll see.

I also tested `tiny`, `base`, and `medium` again and they all exported fine. Exporting `medium` allocated about 23GB peak and finished in about 11 minutes (most of the slowness is due to swapping - the smaller models took less than 30 seconds each).

**Comment by rotemdan** [comment]
After increasing virtual memory to a custom maximum 50GB, the export worked (previous maximum was automatically set to 22GB by Windows system).

The `large-v3` model exported correctly (in 16 minutes, peak 30GB virtual memory) but to 1134 separate files totaling 6GB. The reason for the additional files is that the ONNX runtime uses protocol buffers, which are limited to 2GB in a single buffer, so they have to split larger models to bypass this limitation.

I was able to load and open the exported model in Python (I can't actually test it though).

Unfortunately `onnxrumtime-node` and `onnxruntime-web` [don't currently support models with external data](https://github.com/microsoft/onnxruntime/issues/13006).

In the future, it is possible for them to add support on `onnxrumtime-node`, since [it uses a C binding](https://github.com/microsoft/onnxruntime/blob/main/js/node/src/inference_session_wrap.cc#L51C71-L51C75) (link to source code), and not WebAssembly, but currently there is no support, and there is no issue or discussion specifically about this, that I could find (you can read the one about `onnxruntime-web` [I mentioned earlier](https://github.com/microsoft/onnxruntime/issues/13006)).

So it's effectively impossible to load the model in Node.js at the moment.

However, slightly unrelated, it seems that recently they started adding support for [CUDA and DML on `onnxruntime-node`](https://github.com/microsoft/onnxruntime/pull/16050) (it says currently Windows-only), which would be great in the future ([I'm not sure if it's already deployed](https://github.com/microsoft/onnxruntime/issues/14127) in stable). I don't think this has anything to do with support for large models though.
